version: '3.9'

services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  bff:
    build:
      context: .
      dockerfile: docker/Dockerfile.bff
    environment:
      MONGO_URL: mongodb://mongo:27017/bff
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  microfrontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.microfrontend
    ports:
      - '4200:4200'
      - '4201:4201'
      - '4202:4202'
    depends_on:
      - bff

volumes:
  mongo_data:
