FROM node:20-alpine

WORKDIR /app

COPY package.json /app/package.json
COPY apps/bff/package.json /app/apps/bff/package.json

RUN npm install -g pm2 \
  && npm install --workspace apps/bff

COPY apps/bff /app/apps/bff
COPY docker /app/docker

RUN npm --workspace apps/bff run build

EXPOSE 3000

CMD ["pm2-runtime", "/app/docker/pm2.ecosystem.config.js", "--only", "bff"]
